name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

      - name: Create zip of repository
        run: |
          zip -r openeo-${{ steps.get_tag.outputs.tag_name }}.zip . -x '*.git*' '.github*'
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: openeo-${{ steps.release.outputs.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}

