name: Publish repository as Zip

on:
  push:
    tags:
     - 'v*'

permissions:
  contents: write

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get tag name
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create zip of repository
        run: |
          zip -r openeo-${{ steps.get_tag.outputs.tag_name }}.zip . -x '*.git*' '.github*'

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: openeo-${{ steps.get_tag.outputs.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
